tornado_user:
    resource: "@TornadoUserBundle/Resources/config/routing.yml"
    prefix:   /

tornado_api:
    resource: "@TornadoApiBundle/Resources/config/routing.yml"
    prefix:   /

tornado_site:
    resource: "@TornadoSiteBundle/Resources/config/routing.yml"
    prefix:   /
