Tornado\ApiBundle\Entity\Resource:
    type: entity
    table: tornado
    id:
        id:
            type: integer
            id: true
    fields:
        complexity:
            type: text
            size: medium
        created:
            type: date

    lifecycleCallbacks: {  }
