Tornado\ApiBundle\Entity\Resource:
    type: entity
    table: tornado
    id:
        id:
            type: string
            id: true
    fields:
        complexity:
            type: text
            size: medium
        file:
            type: string
            length: 255
        created:
            type: date

    lifecycleCallbacks: {  }
