Tornado\ApiBundle\Entity\Revision:
    type: entity
    table: revisions

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        entity:
            type: text
            lenght: medium

    manyToOne:
        resource:
            targetEntity: Tornado\ApiBundle\Entity\Resource
            inversedBy: revisions
            joinColumn:
                resource_id:
                    referencedColumnName: id
            cascade:
                - persist

    # manyToOne:
    #     resource_id:
    #         targetEntity: Tornado\ApiBundle\Entity\Resource
    #         joinTable:
    #             name: tornado
    #             joinColumns:
    #                 id:
    #                     referencedColumnName: resource_id

    lifecycleCallbacks: {  }
