tornado_api_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TornadoApiBundle:Default:index }

# Handle file uploads.
tornado_api_file:
  pattern: /api/file
  defaults: { _controller: TornadoApiBundle:Api:file }
  requirements:
    _method: POST

# Handle code blocks.
tornado_api_code:
  pattern: /api/code
  defaults: { _controller: TornadoApiBundle:Api:code }
  requirements:
    _method: POST

# Resource requests
tornado_api_resource_get:
  pattern: /api/resource/{hash}
  defaults: { _controller: TornadoApiBundle:Api:resource }
  requirements:
    _method: GET
