# Handle file uploads.
tornado_api_file:
  pattern: /api/file
  defaults: { _controller: TornadoApiBundle:Api:file }
  requirements:
    _method: POST

# Handle code blocks.
tornado_api_code:
  pattern: /api/code
  defaults: { _controller: TornadoApiBundle:Api:code }
  requirements:
    _method: POST

# Resource requests
tornado_api_resource_get:
  pattern: /api/r/{hash}
  defaults: { _controller: TornadoApiBundle:Api:get }
  requirements:
    _method: GET

# Remove a selected resource.
tornado_api_resource_delete:
  pattern: /api/r/{hash}
  defaults: { _controller: TornadoApiBundle:Api:delete }
  requirements:
    _method: DELETE
