# Handle file uploads.
tornado_api_upload:
  pattern: /api/resource
  defaults: { _controller: TornadoApiBundle:Api:upload }
  methods: [POST]

# Resource requests
tornado_api_resource_get:
  pattern: /api/r/{id}
  defaults: { _controller: TornadoApiBundle:Api:get }
  methods: [GET]

# Property access methods
tornado_api_resource_get_property:
  pattern: /api/r/{id}/{property}
  defaults: { _controller: TornadoApiBundle:Api:getProperty }
  requirements:
    method: GET

# Remove a selected resource.
tornado_api_resource_delete:
  pattern: /api/r/{id}
  defaults: { _controller: TornadoApiBundle:Api:delete }
  requirements:
    method: DELETE
