parameters:
    phploc: 'php %command_dir%/phploc.phar'

services:
    tornado_api.file_manager:
        class: Tornado\ApiBundle\Services\FileManager
        arguments: ['%kernel.root_dir%/../secure', @filesystem]

    tornado_api.command_bag:
        class: Tornado\ApiBundle\Services\CommandBag

    tornado_api.tools.complexity:
        class: Tornado\ApiBundle\Services\Complexity
        arguments: [@filesystem, %phploc%]
        tags:
            - { name: tornado_api.command }


