parameters:
#    tornado_api.example.class: Tornado\ApiBundle\Example

services:
#    tornado_api.example:
#        class: %tornado_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
