tornado_site_homepage:
  pattern:  /
  defaults: { _controller: TornadoSiteBundle:Page:index }

tornado_site_share_page:
  pattern:  /r/{hash}
  defaults: { _controller: TornadoSiteBundle:Page:resource }
  requirements:
    _method: GET

tornado_site_documentation_page:
  pattern: /docs
  defaults: { _controller: TornadoSiteBundle:Page:documentation }
  requirements:
    _method: GET
