tornado_site_homepage:
  pattern:  /
  defaults: { _controller: TornadoSiteBundle:Page:index }

tornado_site_show:
  pattern:  /r/{id}
  defaults: { _controller: TornadoSiteBundle:Page:show }
  requirements:
    _method: GET

tornado_site_documentation_page:
  pattern: /docs
  defaults: { _controller: TornadoSiteBundle:Page:documentation }
  requirements:
    _method: GET
