tornado_user_new:
    pattern: /user/new
    defaults: { _controller: TornadoUserBundle:Default:new }

tornado_user_login:
    pattern: /user/login
    defaults: { _controller: TornadoUserBundle:Default:login }

tornado_user_dashboard:
    pattern: /user
    defaults: { _controller: TornadoUserBundle:Default:dashboard }

tornado_user_new:
    pattern: /_new
    defaults: { _controller: TornadoUserBundle:Default:_new }

tornado_user_new_user:
    pattern: /_dashboard
    defaults: { _controller: TornadoUserBundle:Default:_dashboard }
